#!/bin/bash

git clone git@github.com:perk32725/std.git

# once the project master has been downloaded,
# create a new branch (devel):
git branch devel

# to send the branch upstream <remote repo>, do this:
git push --set-upstream origin devel

# to remove a branch:
git push origin --delete <branch_name>
git branch -d <branch_name>

# to rename current branch:
git branch -m <new_branch>

# to delete a remote branch:
git push origin :<branch_name>

# to place the current new branch:
git push origin <new_branch>

# to rename a remote branch:
# - switch into the new local branch
# - delete the remote branch
# - push the new branch

